### ISSUE TITLE
-e _ not working as expected?

### ISSUE THREAD

**Issue by toddr** [CpanelInc/Overload-FileCheck#7]
I just realized I had a bad test when this failed.
https://travis-ci.org/CpanelInc/Test-MockFile/jobs/446496475

What's concerning here is that Overload::FileCheck shouldn't be passing a query to Test::MockFile for ```-e _```. It should be using the cache to answer the question. Not sure if I'm I misunderstanding how we designed this?

**Comment by atoomic** [comment]
would you have any one-liner to reproduce the bug, thanks?
-e _ is not working the same as stat(_)

**Comment by atoomic** [comment]
closing this issue as the behavior was changed over time and we have no one-liner to reproduce the bug described there.
